name: run-crucible-tracking

on:
  pull_request:
    types: [ opened ]
  issues:
    types: [ opened ]

jobs:
  call-crucible-tracking:
    if: github.repository_owner == 'perftool-incubator'
    uses: ./.github/workflows/crucible-tracking.yaml
    with:
      app_id: ${{ vars.APP_ID__PROJECT_CRUCIBLE_TRACKING }}
    secrets:
      private_key: ${{ secrets.PRIVATE_KEY__PROJECT_CRUCIBLE_TRACKING }}
